### ISSUE TITLE
Proctor Check In Sheet

### ISSUE THREAD

**Issue by MXchuck** [MXchuck/MXMoodle#25]
Proctor Check in Sheet can be made interactive so that you can check the boxes and mark people in.

The report is the form and Proctors would only see their dorm (that's Proctor permission)
Faculty would have permission to manage the form - that would make their dorm the default (or all if they don't have a dorm) and give them the option to filter by other dorms.

**Comment by Cannon544** [comment]
The interactive report is done. All that is needed is to determine in which blocks to link the report, and on what times the attendance data should be reset.
