### ISSUE TITLE
Email option for Approved, Denied

### ISSUE THREAD

**Issue by MXchuck** [MXchuck/MXMoodle#28]
Preferences:
Subj, Body
Metadata tag {alternate name}

**Comment by Cannon544** [comment]
The preferences part is done. Right now it should send an email after the user fills out the COVIDpass, but I'm not sure if it will work, as apparently a localhost moodle server can't send emails

**Comment by jrdegreeff** [comment]
Hey Cannon—I just happened to see this thread, and thought I might interject a thought. Your local server can send emails, but you have to do some configuration. I remember writing something about it in the documentation somewhere, but you will also need a password which is not included anywhere in the repo for probably obvious reasons. Feel free to text/email me or just reply in this thread if you want me to help you set it up at some point.

**Comment by Cannon544** [comment]
Submission emails do in fact work. Thanks Jeremiah!
