### ISSUE TITLE
Table not found - on and off campus

### ISSUE THREAD

**Issue by MXchuck** [MXchuck/MXMoodle#57]
<img width="904" alt="Screen Shot 2020-07-22 at 11 53 33" src="https://user-images.githubusercontent.com/12967566/88198783-0f83e080-cc12-11ea-8619-7d1dc4f11080.png">

**Comment by Cannon544** [comment]
I can't seem to replicate this error on my local server. Other than the possibility of signout not being up to date, I have no idea what's going wrong here.
