### ISSUE TITLE
Certain metadata tags in COVIDpass email do the submitter not working.

### ISSUE THREAD

**Issue by MXchuck** [MXchuck/MXMoodle#67]
This is the email to the submitter.

Each metadata tag was used in the email, in order.
The addressee short and long, email, and name tags seem to be working.

{symptoms} is "None" which is correct.

<img width="528" alt="Screen Shot 2020-07-26 at 07 19 05" src="https://user-images.githubusercontent.com/12967566/88477725-5de5f780-cf10-11ea-8d64-dcf5bb108d3b.png">

**Comment by MXchuck** [comment]
Email sent to the healthcenter for submitter does work

<img width="424" alt="Screen Shot 2020-07-26 at 07 43 43" src="https://user-images.githubusercontent.com/12967566/88478136-d39f9280-cf13-11ea-9f58-856e3ea3c114.png">

**Comment by Cannon544** [comment]
The tags for Healthcenter notification and for the student notifications are different. (student_boarding_status}, {student_phone_number}, {student_dorm}, and {body_temperature}  are only valid tags for the healthcenter notification
